name = "notekori-web"
type = "javascript"
compatibility_date = "2024-03-01"

[build]
command = "npm run build"
cwd = "."
watch_paths = ["src/**/*.ts", "src/**/*.tsx", "public/**/*"]

[build.upload]
format = "service-worker"

[env.production]
name = "notekori-web"
vars = { NEXT_PUBLIC_API_URL = "https://notekori-api.saikat-oubd.workers.dev" }