name = "notekori-web"
compatibility_date = "2024-09-23"
account_id = "ba08e4b771c56e90351420d1a38885db"
main = ".open-next/worker.js"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[env.production]
name = "notekori-web"

[env.production.vars]
NEXT_PUBLIC_ENVIRONMENT = "production"