import { categories } from './schema'

export const DEFAULT_CATEGORIES = [
  // Expense categories
  {
    id: 'sys_food',
    name: 'Food & Dining',
    icon: 'utensils',
    color: '#ef4444',
    type: 'expense' as const,
    userId: 'system',
    isDefault: true,
  },
  {
    id: 'sys_transport',
    name: 'Transport',
    icon: 'car',
    color: '#3b82f6',
    type: 'expense' as const,
    userId: 'system',
    isDefault: true,
  },
  {
    id: 'sys_shopping',
    name: 'Shopping',
    icon: 'shopping-bag',
    color: '#f59e0b',
    type: 'expense' as const,
    userId: 'system',
    isDefault: true,
  },
  {
    id: 'sys_bills',
    name: 'Bills',
    icon: 'receipt',
    color: '#8b5cf6',
    type: 'expense' as const,
    userId: 'system',
    isDefault: true,
  },
  {
    id: 'sys_health',
    name: 'Health',
    icon: 'heart-pulse',
    color: '#ec4899',
    type: 'expense' as const,
    userId: 'system',
    isDefault: true,
  },
  {
    id: 'sys_rent',
    name: 'Rent',
    icon: 'home',
    color: '#06b6d4',
    type: 'expense' as const,
    userId: 'system',
    isDefault: true,
  },
  {
    id: 'sys_entertain',
    name: 'Entertainment',
    icon: 'clapperboard',
    color: '#f97316',
    type: 'expense' as const,
    userId: 'system',
    isDefault: true,
  },
  {
    id: 'sys_education',
    name: 'Education',
    icon: 'graduation-cap',
    color: '#10b981',
    type: 'expense' as const,
    userId: 'system',
    isDefault: true,
  },
  // Income categories
  {
    id: 'sys_salary',
    name: 'Salary',
    icon: 'briefcase',
    color: '#22c55e',
    type: 'income' as const,
    userId: 'system',
    isDefault: true,
  },
  {
    id: 'sys_freelance',
    name: 'Freelance',
    icon: 'laptop',
    color: '#6366f1',
    type: 'income' as const,
    userId: 'system',
    isDefault: true,
  },
  {
    id: 'sys_business',
    name: 'Business',
    icon: 'store',
    color: '#eab308',
    type: 'income' as const,
    userId: 'system',
    isDefault: true,
  },
  {
    id: 'sys_invest',
    name: 'Investment',
    icon: 'trending-up',
    color: '#14b8a6',
    type: 'income' as const,
    userId: 'system',
    isDefault: true,
  },
  {
    id: 'sys_gift',
    name: 'Gift',
    icon: 'gift',
    color: '#f43f5e',
    type: 'income' as const,
    userId: 'system',
    isDefault: true,
  },
] as const
